# Generated by Django 4.2 on 2023-05-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sisestatav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('võlgneja', models.CharField(max_length=100)),
                ('makstav', models.CharField(max_length=100)),
                ('väärtus', models.IntegerField(default=0)),
                ('kirjeldus', models.CharField(max_length=200)),
            ],
        ),
    ]
