# Generated by Django 4.2 on 2023-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kulutustekalkulaator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tulemus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('väärtus', models.IntegerField(default=0)),
            ],
        ),
    ]
